source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

########################
###### FRONT END #######
########################

# JS & Assets Related
gem 'gentelella-rails'                                            # Gentelella Theme
gem 'bootstrap', '~> 4.0.0.alpha6'                                # Bootstrap 4
gem 'font-awesome-sass'                                           # Font Awesome
gem 'jquery-rails', '~> 4.1.1'                                    # JQuery
gem 'jquery-ui-rails', '~> 6.0.1'                                 # JQuery Helpers
gem 'turbolinks', '~> 5'                                          # Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'introjs-rails'                                               # Used for Intros

# Utility
gem 'rack-pjax'                                                   # PJax to make page loading faster
gem 'active_device'                                               # For Mobile / Desktop Web Detection
gem 'best_in_place'                                               # In place editing for Text Fields
# gem 'paul_revere', '~> 2.0.0'                                   # For Announcements on The Website

group :assets do
  gem 'sass-rails', '~> 5.0'                                      # Use SCSS for stylesheets
  gem 'compass-rails'                                             # Framework of SCSS for rails
  gem 'uglifier', '>= 1.3.0'                                      # Use uglifier as compressor for JavaScript assets
  gem 'coffee-rails', '~> 4.2'                                    # Use CoffeeScript for .coffee assets and views
  gem 'therubyracer', platforms: :ruby                            # Execute Javascript in Ruby
end


########################
###### BACK END #######
########################

# Server Related
gem 'rails', '~> 5.0.2'                                           # Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'pg'                                                          # Use Postgres as the database for Active Record
# gem 'capistrano'                                                 # Auto Deploy Projects
gem 'sidekiq'                                                     # For Background services

# Authorization
gem 'devise'                                                      # For Login system
gem 'devise-async'                                                # For Sending Emails
# gem 'devise-token_authenticatable'                                # Authenticating based on Tokens
gem 'omniauth'                                                    # For login from social websites
gem 'omniauth-google-oauth2'                                      # For login from google
gem 'omniauth-facebook'                                           # For login from facebook
gem 'recaptcha', require: 'recaptcha/rails'                       # Creating Recaptchas

# Cache
# gem 'dalli'                                                     # For caching

# Utility
gem 'pdf-reader'                                                  # For reading PDFS
gem 'docsplit'                                                    # For Splitting Documents
gem 'i18n-js', '>= 3.0.0.rc11'
gem 'hashie'                                                      # Getting hashes
gem 'rack-cors'                                                   # Handling Cross Origin Requests
gem 'paperclip'                                                   # File attachement
gem 'jquery-fileupload-rails'                                     # Uploading images / files
gem 'geocoder'                                                    # Translate address into lon and lat 
# gem 'public_activity'                                           # For Notifications
# gem 'has_easy', '~> 0.9.0', github: 'aafaq-hassan/has_easy'     # User Properties

# Misc
# gem 'sitemap_generator'                                         # For Generating Sitemaps for Google etc.

group :development, :test do
  gem 'rdoc'                                                      # For Generating Documentation (Requires GraphViz Local Install)
  gem 'rails-erd'                                                 # For Generating ERD Diagrams (https://github.com/voormedia/rails-erd)
  gem 'annotate'                                                  # Adding annotations to models (http://github.com/ctran/annotate_models)
  gem 'byebug', platform: :mri                                    # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'passenger', '~> 5.0.7'                                     # Web Server (Best)
  #gem 'puma', '~> 2.8.1'                                         # Web Server (Lighter)
end

group :development do
  gem 'web-console', '>= 3.3.0'                                   # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  # gem 'spring'                                                    # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  # gem 'spring-watcher-listen', '~> 2.0.0'

  gem 'ruby-lint'                                                 # For Detecting any mistakes in Ruby Code
  gem 'bullet'                                                    # For Avoiding N+1 Queries
end